Web/RPM.Web/Controllers/CheckoutController.cs
namespace RPM.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Data.Models;
    using RPM.Data.Models.Enums;
    using RPM.Services.Common;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Payment;
    using RPM.Web.Models.Profile;
    using Stripe;
    using Stripe.Checkout;

    using static RPM.Common.GlobalConstants;

    [Authorize(Roles = "Tenant, Owner")]
    public class CheckoutController : BaseController
    {
        private readonly UserManager<User> userManager;
        private readonly IPaymentCommonService paymentCommonService;

        public CheckoutController(
            UserManager<User> userManager,
            IPaymentCommonService paymentCommonService)
        {
            this.userManager = userManager;
            this.paymentCommonService = paymentCommonService;
        }

        public async Task<IActionResult> Success(string sessionId)
        {
            var userId = this.userManager.GetUserId(this.User);
            bool compare = await this.paymentCommonService.CompareData(sessionId);

            if (string.IsNullOrWhiteSpace(sessionId) || compare == false)
            {
                return this.RedirectToAction(nameof(ProfileController.Index), "Home", new { area = string.Empty })
                    .WithWarning(string.Empty, NiceTry);
            }

            var paymentId = await this.paymentCommonService.GetPaymentId(sessionId);

            var model = await this.paymentCommonService.GetPaymentDetailsAsync(paymentId, userId);

            var viewModel = new CheckoutPaymentViewModel
            {
                Reason = model.Reason,
                Amount = model.Amount,
                To = model.To,
                Address = model.Address,
                TransactionDate = model.TransactionDate?.ToString(DateFormatWithTime),
            };

            return this.View(viewModel);
        }
    }
}

Web/RPM.Web/Controllers/DashboardController.cs
namespace RPM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Data.Models;
    using RPM.Services.Common;
    using RPM.Services.Common.Models.Home;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Dashboard;
    using Stripe;
    using Stripe.Checkout;
    using static RPM.Common.GlobalConstants;

    public class DashboardController : BaseController
    {
        private readonly UserManager<User> userManager;
        private readonly IListingService listingService;
        private readonly IPaymentCommonService paymentService;

        public DashboardController(
            UserManager<User> userManager,
            IListingService listingService,
            IPaymentCommonService paymentService)
        {
            this.userManager = userManager;
            this.listingService = listingService;
            this.paymentService = paymentService;
        }

        [Authorize(Roles = ManagerRoleName)]
        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(this.User);
            var user = await this.userManager.FindByIdAsync(userId);
            var hasStripe = !string.IsNullOrWhiteSpace(user.StripeConnectedAccountId);

            var userPayments = await this.paymentService.GetManagerPaymentsListAsync(userId);
            var managedProperties = await this.listingService.GetManagedPropertiesAsync(userId);

            var viewModel = new ManagerDashboardViewModel
            {
                HasStripeAccount = hasStripe,
                ManagedProperties = managedProperties,
                Payments = userPayments,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Pay(string paymentId, string stripeToken)
        {
            var userId = this.userManager.GetUserId(this.User);
            var payment = await this.paymentService.GetPaymentDetailsAsync(paymentId, userId);

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                },

                PaymentIntentData = new SessionPaymentIntentDataOptions
                {
                    ApplicationFeeAmount = (long)((payment.Amount * 0.01m) * 100),
                    Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",
                    CaptureMethod = "manual",

                    TransferData = new SessionPaymentIntentTransferDataOptions
                    {
                        Amount = (long)payment.Amount * 100,
                        Destination = payment.ToStripeAccountId,
                    },
                },

                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Name = "Monthly Rent",
                        Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",
                        Amount = (long)payment.Amount * 100,
                        Currency = CurrencyUSD,
                    },
                },
                SuccessUrl = "https://localhost:44319/Management/Stripe/Checkout/success?session_id={CHECKOUT_SESSION_ID}",
                CancelUrl = "https://localhost:44319/Management/Stripe/Checkout/cancel",
            };

            var service = new SessionService();
            Session session = service.Create(options);

            return this.RedirectToAction("Success", new { session_id = session.Id });
        }
    }
}

Web/RPM.Web/Controllers/ProfileController.cs
namespace RPM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Data;
    using RPM.Data.Models;
    using RPM.Data.Models.Enums;
    using RPM.Services.Common;
    using RPM.Services.Common.Models.Home;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Home;
    using RPM.Web.Models.Profile;
    using RPM.Web.ViewModels;
    using Stripe;
    using Stripe.Checkout;
    using static RPM.Common.GlobalConstants;

    [Authorize(Roles = TenantRole)]
    public class ProfileController : BaseController
    {
        private readonly UserManager<User> userManager;
        private readonly IPaymentCommonService paymentService;
        private readonly IRentalService rentalService;

        public ProfileController(
            UserManager<User> userManager,
            IPaymentCommonService paymentService,
            IRentalService rentalService)
        {
            this.userManager = userManager;
            this.paymentService = paymentService;
            this.rentalService = rentalService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(this.User);

            var userPayments = await this.paymentService.GetUserPaymentsListAsync(userId);

            var userRentals = await this.rentalService.GetUserRentalsListAsync(userId);
            var viewModel = new ProfileIndexViewModel
            {
                Payments = userPayments,
                Rentals = userRentals,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Pay(string paymentId, string stripeToken)
        {
            var userId = this.userManager.GetUserId(this.User);
            var payment = await this.paymentService.GetPaymentDetailsAsync(paymentId, userId);

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                },

                PaymentIntentData = new SessionPaymentIntentDataOptions
                {
                    ApplicationFeeAmount = (long)((payment.Amount * 0.01m) * 100),
                    Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",
                    CaptureMethod = "manual",

                    TransferData = new SessionPaymentIntentTransferDataOptions
                    {
                        Amount = (long)payment.Amount * 100,
                        Destination = payment.ToStripeAccountId,
                    },
                },

                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Name = "Monthly Rent",
                        Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",
                        Amount = (long)payment.Amount * 100,
                        Currency = CurrencyUSD,
                    },
                },
                SuccessUrl = "https://localhost:44319/Management/Stripe/Checkout/success?session_id={CHECKOUT_SESSION_ID}",
                CancelUrl = "https://localhost:44319/Management/Stripe/Checkout/cancel",
            };

            var service = new SessionService();
            Session session = service.Create(options);

            return this.RedirectToAction("Success", new { session_id = session.Id });
        }
    }
}

Web/RPM.Web/Views/Checkout/Success.cshtml
@model CheckoutPaymentViewModel

@{
    ViewData["Title"] = "Success";
    if (this.User.IsInRole(OwnerRoleName))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

@if (this.User.IsInRole(OwnerRoleName))
{
    @await Html.PartialAsync("_OwnerSuccessPartial", Model)
}
else
{
    <body class="handshake-bg">
        <section class="content pb-4"
                 style="padding-top: 120px; margin-left: auto; margin-right: auto;">
            <div class="row d-flex justify-content-center">

                <div class="row p-3 mx-auto mt-4">
                    <div class="form-area">
                        <div class="col-md-12 pb-4">
                            <p>
                                <a class="primary-btn px-1 bg-transparent text-primary">
                                    Thank you! Your payment was successful!
                                </a>
                            </p>
                            <ul class="pb-4 mb-4">
                                @*<li><strong>Payment reason:</strong> Model.Reason</li>
                                    <li><strong>Amount paid:</strong> Model.Amount</li>
                                    <li><strong>Recipient:</strong> Model.To</li>*@
                                <li><strong>Payment reason:</strong> @Model.Reason</li>
                                <li><strong>Amount paid:</strong> $ @Model.Amount</li>
                                <li><strong>Recipient:</strong> @Model.To</li>
                                <li><strong>Property Address:</strong> @Model.Address</li>
                                @*<li><strong>Transaction Date:</strong> @Model.TransactionDate</li>*@
                            </ul>
                        </div>
                        @if (this.User.IsInRole(OwnerRoleName))
                        {
                            <div class="col-md-6 pt-4 mt-4 mx-auto">
                                <a asp-area="Management"
                                   asp-controller="Dashboard"
                                   asp-action="Index"
                                   class="shadow btn btn-block btn-primary text-white">
                                    Back to Dashboard
                                </a>
                            </div>
                        }
                        else
                        {
                            <div class="col-md-6 pt-4 mt-4 mx-auto">
                                <a asp-controller="Profile"
                                   asp-action="Index"
                                   class="shadow btn btn-block btn-primary text-white">
                                    Back to Profile
                                </a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </section>
    </body>
}