Web/RPM.Web/Areas/Administration/Models/Cities/AdminCityAndCountryInputModel.cs
namespace RPM.Services.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using RPM.Data.Models;

    public class AdminCityAndCountryViewModel
    {
        public City City { get; set; }

        public IEnumerable<Country> CountryList { get; set; }

        public List<string> CityList { get; set; }

        public string StatusMessage { get; set; }
    }
}

Web/RPM.Web/Areas/Administration/Models/Cities/AdminCityAndCountryViewModel.cs
namespace RPM.Services.Admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using RPM.Data.Models;

    public class AdminCityAndCountryViewModel
    {
        public City City { get; set; }

        public IEnumerable<Country> CountryList { get; set; }

        public List<string> CityList { get; set; }

        public string StatusMessage { get; set; }
    }
}

Web/RPM.Web/Areas/Administration/Models/CityViewModel.cs
namespace RPM.Web.Areas.Administration.Models
{
    public class CityViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

    }
}

Web/RPM.Web/Areas/Administration/Controllers/CitiesController.cs
namespace RPM.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Services.Admin;
    using RPM.Services.Admin.Models;
    using RPM.Web.Areas.Administration.Models.Cities;
    using RPM.Web.Infrastructure.Extensions;

    using static RPM.Common.GlobalConstants;

    public class CitiesController : AdministrationController
    {
        private readonly IAdminCityService adminCityService;

        public CitiesController(IAdminCityService adminCityService)
        {
            this.adminCityService = adminCityService;
        }

        [TempData]
        public string StatusMessage { get; set; }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            var model = await this.adminCityService.AllCitiesAsync();

            return this.View(model);
        }

        // GET: Cities/Create
        public async Task<IActionResult> Create()
        {
            var model = await this.adminCityService.GetCreateAsync();

            return this.View(model);
        }

        // POST: Cities/Create
        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> CreateAsync(AdminCityAndCountryInputModel model)
        {
            var modelVM = await this.adminCityService.GetCreateAsync();

            if (this.ModelState.IsValid)
            {
                var cityExists = await this.adminCityService.CreateAsync(model.City.Name, model.City.CountryId);

                if (cityExists == null)
                {
                    this.StatusMessage = RecordAlreadyExists;

                    modelVM.City = model.City;
                    modelVM.StatusMessage = this.StatusMessage;

                    return this.View(modelVM);
                }

                return this.RedirectToAction(nameof(this.Index))
                    .WithSuccess(string.Empty, RecordCreatedSuccessfully);
            }

            return this.View(modelVM);
        }

        // GET: Cities/Edit/5
        public async Task<ActionResult> EditAsync(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var model = await this.adminCityService.GetUpdateAsync(id);

            if (model == null)
            {
                return this.NotFound();
            }

            return this.View(model);
        }

        // POST: Cities/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> EditPostAsync(int? id, AdminCityEditDeleteServiceModel model)
        {
            if (this.ModelState.IsValid)
            {
                bool isEdited = await this.adminCityService.UpdateAsync(id, model.City.Name);

                if (!isEdited)
                {
                    this.StatusMessage = CouldNotUpdateRecord;
                    var modelVM = await this.adminCityService.GetUpdateAsync(id);
                    modelVM.StatusMessage = this.StatusMessage;

                    return this.View(modelVM);
                }

                return this.RedirectToAction(nameof(this.Index))
                    .WithSuccess(string.Empty, RecordUpdatedSuccessfully);
            }

            return this.RedirectToAction(nameof(this.Index))
                        .WithWarning(string.Empty, RecordIdIsInvalid);
        }

        // GET - Delete
        public async Task<IActionResult> DeleteAsync(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var model = await this.adminCityService.GetByIdAsync(id);

            return this.View(model);
        }

        // POST - Delete
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePostAsync(int? id)
        {
            if (this.ModelState.IsValid)
            {
                bool isDeleted = await this.adminCityService.DeleteAsync(id);

                if (!isDeleted)
                {
                    this.StatusMessage = DeltionDenied;
                    var modelVM = await this.adminCityService.GetByIdAsync(id);
                    modelVM.StatusMessage = this.StatusMessage;

                    return this.View(modelVM);
                }

                return this.RedirectToAction(nameof(this.Index))
                    .WithSuccess(string.Empty, RecordDeletedSuccessfully);
            }

            return this.RedirectToAction(nameof(this.Index))
                        .WithWarning(string.Empty, RecordIdIsInvalid);
        }
    }
}

Web/RPM.Web/Areas/Administration/Views/Cities/Create.cshtml
@using static RPM.Common.Extensions.EnumerableExtensionMethod

@model AdminCityAndCountryInputModel
@{
    ViewData["Title"] = "City Administration";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<body>
    <div class="content-wrapper">
        <h2 class="text-left pl-3 pt-2">@ViewData["Title"]</h2>
        <br />
        <br />
        <partial name="_StatusMessagePartial" model="Model.StatusMessage" />
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header" style="background-color: #17A2B8">
                                <h3 class="card-title">Add City to List</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" asp-controller="Cities" asp-action="Create">
                                <div class="card-body">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="City.Name">City Name</label>
                                        <input asp-for="City.Name" class="form-control" placeholder="City name">
                                        <span asp-validation-for="City.Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="City.CountryId">Country</label>
                                        <select id="ddlCountryList" asp-for="City.CountryId" asp-items="Model.CountryList.ToSelectListItem(Model.City.CountryId)" class="form-control col-6"></select>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <partial name="_ButtonCreateAndBackToListPartial" />
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                    <div class="col-md-3 offset-1">
                        @if (Model.CityList.Count() > 0)
                        {
                            <div class="card card-primary">
                                <div class="card-header" style="background-color: #17A2B8">
                                    <h3 class="card-title">Existing Cities</h3>
                                </div>
                                <!-- /.card-header -->
                                <div id="CityList">
                                    <ul class="list-group">
                                        @foreach (var city in Model.CityList)
                                        {
                                            <li class="list-group-item text-info">@city</li>
                                        }
                                    </ul>
                                </div>

                            </div>
                            <!-- /.card -->
                        }
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
    </div>
</body>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        function updateCityList() {
            var countrySelected = document.getElementById("ddlCountryList").value;

            $list = $('#CityList');

            $.ajax({
                url: '/Administration/Cities/Create/' + countrySelected,
                type: 'GET',
                dataType: 'text',
                success: function (data) {
                    results = JSON.parse(data);
                    $list.html('');
                    $list.append(' <ul class="list-group"> ');
                    for (i in results) {
                        $list.append('<li class="list-group-item">' + results[i].text + '</li>');
                    }
                    $list.append('</ul>');
                }
            });
        }

        $(document).ready(function () {
            updateCityList();
        });

        $("#ddlCountryList").on("change", function () {
            updateCityList();
        });

    </script>
}

Web/RPM.Web/Areas/Administration/Views/Cities/Delete.cshtml
@model AdminCityDetailsServiceModel
@{
    ViewData["Title"] = "Country Administration";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<body>
    <div class="content-wrapper">
        <h2 class="text-left pl-3 pt-2">@ViewData["Title"]</h2>
        <br />
        <br />
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header" style="background-color: #17A2B8">
                                <h3 class="card-title">Remove City from List</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" asp-controller="Cities" asp-action="Delete">
                                <div class="card-body">
                                    <input type="hidden" asp-for="Id" />
                                    <div class="form-group">
                                        <label asp-for="Name">City Name</label>
                                        <input disabled asp-for="Name" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Country">Country</label>
                                        <input disabled type="text" asp-for="Country" class="form-control col-6">
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <partial name="_ButtonDeleteAndBackToListPartial" model="Model.Id" />
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
    </div>
</body>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/RPM.Web/Areas/Administration/Views/Cities/Edit.cshtml
@model AdminCityEditDeleteServiceModel
@{
    ViewData["Title"] = "Country Administration";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<body>
    <div class="content-wrapper">
        <h2 class="text-left pl-3 pt-2">@ViewData["Title"]</h2>
        <br />
        <br />
        <partial name="_StatusMessagePartial" model="Model.StatusMessage" />
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header" style="background-color: #17A2B8">
                                <h3 class="card-title">Edit City</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" asp-controller="Cities" asp-action="Edit">
                                <div class="card-body">
                                    <input type="hidden" asp-for="City.Id" />
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="City.Name">City Name</label>
                                        <input asp-for="City.Name" class="form-control">
                                        <span asp-validation-for="City.Name" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Country">Country</label>
                                        <input type="text" asp-for="Country" class="form-control col-6" disabled>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                                <div class="card-footer">
                                    <partial name="_ButtonEditAndBackToListPartial" model="Model.City.Id" />
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                    <!--/.col (left) -->
                    <div class="col-md-3 offset-1">
                        @if (Model.CityList.Count() > 0)
                        {
                            <div class="card card-primary">
                                <div class="card-header" style="background-color: #17A2B8">
                                    <h3 class="card-title">Existing Cities</h3>
                                </div>
                                <!-- /.card-header -->
                                <div id="CityList">
                                    <ul class="list-group">
                                        @foreach (var city in Model.CityList)
                                        {
                                            <li class="list-group-item text-info">@city</li>
                                        }
                                    </ul>
                                </div>

                            </div>
                            <!-- /.card -->
                        }
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
    </div>
</body>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/RPM.Web/Areas/Administration/Views/Cities/Index.cshtml
@using RPM.Services.Admin.Models
@model IEnumerable<AdminCitiesListingServiceModel>
@{
    ViewData["Title"] = "Cities Administration";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<head>
    <!-- DataTables -->
    <link rel="stylesheet" href="~/themes/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
</head>

<body>
    <div class="content-wrapper">
        <h2 class="text-center pl-2 pt-2">@ViewData["Title"]</h2>
        <section class="content">
            <div class="row justify-content-center">
                <div class="col-8 pt-4">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-6">
                                    <h2 class="card-title text-info"><strong>Cities List</strong></h2>
                                </div>
                                <div class="col-6 text-right">
                                    <partial name="_ButtonCreatePartial" />
                                </div>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            @if (Model.Count() > 0)
                            {
                                <table id="mytable" class="table table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>@Html.DisplayNameFor(c => c.Id)</th>
                                            <th>@Html.DisplayNameFor(c => c.Name)</th>
                                            <th>@Html.DisplayNameFor(c => c.Country)</th>
                                            <th class="text-center">Manage</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var city in Model)
                                        {
                                            <tr>
                                                <td class="col-md-1">@city.Id</td>
                                                <td>@city.Name</td>
                                                <td>@city.Country</td>
                                                <td style="width:100px">
                                                    <div class="btn btn-group" role="group">
                                                        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@city.Id">
                                                            <i class="far fa-edit"></i>
                                                        </a>
                                                        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@city.Id">
                                                            <i class="far fa-trash-alt"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>

                                </table>
                            }
                            else
                            {
                                <h2 class="text-danger">Oops, no records in the database !</h2>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- DataTables -->
    <script src="~/themes/admin/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/themes/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
</body>
<!-- page script -->
@section Scripts{
    <script>
        $(function () {
            $('#mytable').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": true,
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            var table = $('#mytable').dataTable();
            table.fnPageChange('next');
        });
    </script>
}