Web/RPM.Web/Areas/Management/Models/Payments/OwnerAllPaymentsViewModel.cs
namespace RPM.Web.Areas.Management.Models.Payments
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using RPM.Services.Management.Models;

    public class OwnerAllPaymentsViewModel
    {
        public IEnumerable<OwnerAllPaymentsServiceModel> Payments { get; set; }
    }
}

Web/RPM.Web/Models/Payment/CheckoutPaymentViewModel.cs
namespace RPM.Web.Models.Payment
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using RPM.Data.Models.Enums;

    public class CheckoutPaymentViewModel
    {
        public string Id { get; set; }

        public DateTime Date { get; set; }

        public string TransactionDate { get; set; }

        public string To { get; set; }

        public string ToStripeAccountId { get; set; }

        public string Reason { get; set; }

        public decimal? Amount { get; set; }

        public PaymentStatus Status { get; set; }

        public string Address { get; set; }
    }
}

Web/RPM.Web/Areas/Management/Controllers/PaymentsController.cs
namespace RPM.Web.Areas.Management.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Hangfire;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Data;
    using RPM.Data.Models;
    using RPM.Data.Models.Enums;
    using RPM.Services.Common;
    using RPM.Services.Management;
    using RPM.Services.Management.Implementations;
    using RPM.Web.Areas.Management.Models.Payments;
    using RPM.Web.Areas.Management.Models.Requests;
    using RPM.Web.Areas.Management.Models.TransactionRequests;
    using RPM.Web.Infrastructure.Extensions;
    using Stripe;
    using Stripe.Checkout;

    using static RPM.Common.GlobalConstants;

    [Authorize(Roles = "Owner, Tenant")]
    public class PaymentsController : ManagementController
    {
        private readonly ApplicationDbContext context;
        private readonly UserManager<User> userManager;
        private readonly IOwnerPaymentService paymentService;
        private readonly IPaymentCommonService paymentCommonService;

        public PaymentsController(
            ApplicationDbContext context,
            UserManager<User> userManager,
            IOwnerPaymentService paymentService,
            IPaymentCommonService paymentCommonService)
        {
            this.context = context;
            this.userManager = userManager;
            this.paymentService = paymentService;
            this.paymentCommonService = paymentCommonService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = await this.paymentService
                .AllPayments(userId);

            var viewModel = new OwnerAllPaymentsViewModel
            {
                Payments = model,
            };

            return this.View(viewModel);
        }

        [ActionName("session")]
        public async Task<IActionResult> CreateSession(string id)
        {
            var userId = this.userManager.GetUserId(this.User);
            var payment = await this.paymentService.GetPaymentDetailsAsync(id, userId);

            //// LOCALHOST LINKS
            // var successStringUrl = "https://localhost:44319/checkout/success?sessionId={CHECKOUT_SESSION_ID}";
            // var cancelStringUrl = "https://localhost:44319/checkout/cancel";

            // AZURE LINKS
            // LOCALHOST LINKS
            var successStringUrl = "https://homy.azurewebsites.net/checkout/success?sessionId={CHECKOUT_SESSION_ID}";
            var cancelStringUrl = "https://homy.azurewebsites.net/checkout/cancel";

            //// CONVEYOR LINKS
            // var successStringUrl = "https://rpm-web.conveyor.cloud/checkout/success?sessionId={CHECKOUT_SESSION_ID}";
            // var cancelStringUrl = "https://rpm-web.conveyor.cloud/checkout/cancel";

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                },

                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Quantity = 1,
                        Amount = (long)payment.Amount * 100,
                        Currency = CurrencyUSD,

                        Name = $"Rent Payment for {DateTime.UtcNow.ToString("MMMM")}/ {DateTime.UtcNow.Year} at {payment.Address}",
                    },
                },

                PaymentIntentData = new SessionPaymentIntentDataOptions
                {
                    ApplicationFeeAmount = (long)((payment.Amount * 0.01m) * 100),
                    CaptureMethod = "automatic",
                    Description = payment.Id,

                    TransferData = new SessionPaymentIntentTransferDataOptions
                    {
                        Destination = payment.ToStripeAccountId,
                    },
                },

                SuccessUrl = successStringUrl,
                CancelUrl = cancelStringUrl,
            };

            var service = new SessionService();
            Session session = service.Create(options);

            // Create Checkout Session in Database to validate it the Webhook handler and in SuccessPage
            await this.paymentCommonService.CreateCheckoutSessionAsync(session.Id, payment.Id, payment.ToStripeAccountId);

            return this.Json(session);
        }
    }
}

Web/RPM.Web/Controllers/PaymentController.cs
namespace RPM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Data.Models;
    using RPM.Services.Common;
    using RPM.Services.Common.Models.Home;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Home;
    using RPM.Web.Models.Payment;
    using RPM.Web.ViewModels;

    using Stripe;
    using Stripe.Checkout;

    using static RPM.Common.GlobalConstants;

    [Authorize(Roles = "Owner, Tenant")]
    public class PaymentController : BaseController
    {
        private readonly UserManager<User> userManager;
        private readonly IPaymentCommonService paymentService;

        public PaymentController(
            UserManager<User> userManager,
            IPaymentCommonService paymentService)
        {
            this.userManager = userManager;
            this.paymentService = paymentService;
        }

        public async Task<IActionResult> Pay(string id)
        {
            var userId = this.userManager.GetUserId(this.User);

            var payment = await this.paymentService.GetPaymentDetailsAsync(id, userId);

            if (payment.RecipientHasStripeAccount == false && this.User.IsInRole(OwnerRoleName))
            {
                return this.RedirectToAction("Index", "Dashboard", new { area = ManagementArea })
                    .WithWarning(string.Empty, string.Format(ManagerHasNotStripeAccount, payment.To));
            }

            var viewModel = new CheckoutPaymentViewModel
            {
                Id = payment.Id,
                Date = payment.Date,
                To = payment.To,
                ToStripeAccountId = payment.ToStripeAccountId,
                Reason = payment.Reason,
                Amount = payment.Amount,
                Status = payment.Status,
                Address = payment.Address,
            };

            return this.View(viewModel);
        }

        // REMOVE WHEN ALL IS OVER - WORKING METHOD IS IN MANAGEMENT AREA
        [HttpPost]
        [Route("createsession")]
        public async Task<IActionResult> CreateSession()
        {
            var id = "68f51bff-5709-4337-a74b-d0ecb53f33ec";
            var userId = this.userManager.GetUserId(this.User);
            var payment = await this.paymentService.GetPaymentDetailsAsync(id, userId);

            var successStringUrl = "https://localhost:44319/Checkout/success?session_id={CHECKOUT_SESSION_ID}";
            var cancelStringUrl = "https://localhost:44319/Checkout/cancel?";

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                },

                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Quantity = 1,
                        Amount = (long)payment.Amount * 100,
                        Currency = CurrencyUSD,

                        Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",

                        Name = $"Rent Payment for {DateTime.UtcNow.Month} | {DateTime.UtcNow.Year} for rental at {payment.Address}",
                    },
                },

                PaymentIntentData = new SessionPaymentIntentDataOptions
                {
                    ApplicationFeeAmount = (long)((payment.Amount * 0.01m) * 100),
                    CaptureMethod = "manual",

                    TransferData = new SessionPaymentIntentTransferDataOptions
                    {
                        Destination = payment.ToStripeAccountId,
                    },
                },

                SuccessUrl = successStringUrl,
                CancelUrl = cancelStringUrl,
            };

            var service = new SessionService();
            Session session = service.Create(options);

            return this.Json(session);
        }
    }
}

Web/RPM.Web/Controllers/RentalsController.cs
namespace RPM.Web.Controllers
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Http;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Common.Extensions;
    using RPM.Data.Models;
    using RPM.Data.Models.Enums;
    using RPM.Services.Common;
    using RPM.Services.Common.Models.Request;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Requests;

    using static RPM.Common.GlobalConstants;

    [Authorize(Roles = TenantRole)]
    public class RentalsController : BaseController
    {
        private readonly UserManager<User> userManager;
        private readonly IRentalService rentalService;
        private readonly IListingService listingService;
        private readonly IRequestService requestService;

        public RentalsController(
            UserManager<User> userManager,
            IRentalService rentalService,
            IListingService listingService,
            IRequestService requestService)
        {
            this.userManager = userManager;
            this.rentalService = rentalService;
            this.listingService = listingService;
            this.requestService = requestService;
        }

        [ActionName("Details")]
        public async Task<IActionResult> DetailsAsync(int id)
        {

            var user = await this.userManager.GetUserAsync(this.User);
            var userId = user.Id;

            var model = await this.rentalService.GetDetailsAsync(id);

            var viewModel = new CancellationRequestInputModel
            {
                RentalInfo = model,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [ActionName("Details")]
        public async Task<IActionResult> CancelRentAsync(int id, string message, IFormFile document)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction("Index", "Profile", new { area = string.Empty })
                    .WithWarning(string.Empty, InvalidEntryData);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            var homeFromDb = await this.rentalService.GetDetailsAsync(id);
            var fileContents = await document.ToByteArrayAsync();

            var modelForDb = new RequestCreateServiceModel
            {
                Date = DateTime.UtcNow,
                Type = RequestType.CancelRent,
                UserId = user.Id,
                Message = message,
                HomeId = homeFromDb.HomeId,
                Document = fileContents,
            };

            bool isCreated = await this.requestService.CreateRequestAsync(modelForDb);

            if (isCreated)
            {
                return this.RedirectToAction("Index", "Profile", new { area = string.Empty })
                    .WithSuccess(string.Empty, SuccessfullySubmittedRequest);
            }

            return this.RedirectToAction("Index", "Profile", new { area = string.Empty })
                    .WithDanger(string.Empty, FailedToSubmitRequest);
        }
    }
}

Web/RPM.Web/Views/Payment/Pay.cshtml
@using Microsoft.Extensions.Options

@model CheckoutPaymentViewModel

@{
    ViewData["Title"] = "Pay";
    if (this.User.IsInRole(OwnerRoleName))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

@if (this.User.IsInRole(OwnerRoleName))
{
    <div class="content-wrapper">
        <section class="content">
            <div class="row d-flex justify-content-center">
                <div class="col-md-5 pl-4 py-xl-4">
                    <div class="card shadow">
                        <div class="card-header border-transparent text-center">
                            <h3 class="card-title text-info">
                                <a class="text-info">
                                    <strong>@Model.Address</strong>
                                </a>
                            </h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">

                            <div class="row px-3">
                                <div class="col-6 text-center">
                                    <strong><i class="far fa-calendar-alt mr-1"></i>Payment Request Date</strong>
                                    <div class="row">
                                        <div class="col-12">
                                            <hr class="hr-2 mt-1" />
                                        </div>
                                    </div>
                                    <p class="text-muted">
                                        @Model.Date
                                    </p>
                                </div>
                                <div class="col-6 text-center">
                                    <strong><i class="far fa-file-alt mr-1"></i>Reason</strong>
                                    <div class="row">
                                        <div class="col-12">
                                            <hr class="hr-2 mt-1" />
                                        </div>
                                    </div>
                                    <p class="text-muted">
                                        @Model.Reason
                                    </p>
                                </div>
                            </div>

                            <div class="row px-3">
                                <div class="col-6 text-center">
                                    <strong><i class="fas fa-user-tie mr-1"></i>Pay To</strong>
                                    <div class="row">
                                        <div class="col-12">
                                            <hr class="hr-2 mt-1" />
                                        </div>
                                    </div>
                                    <p class="text-muted">
                                        @Model.To
                                    </p>
                                </div>
                                <div class="col-6 text-center">
                                    <strong><i class="far fa-file-alt mr-1"></i>Status</strong>
                                    <div class="row">
                                        <div class="col-12">
                                            <hr class="hr-2 mt-1" />
                                        </div>
                                    </div>
                                    <span class="badge badge-danger">Pending</span>
                                </div>
                            </div>

                        </div>
                        <!-- /.card-body -->
                        <!-- /.card-footer -->
                        <script src="https://js.stripe.com/v3/"></script>
                        <div id="checkout">
                            <form id="payment-form">
                                <div class="row d-flex justify-content-center">
                                    <div class="col-6 py-4 text-center">
                                        <button id="checkout-button"
                                                value="Pay"
                                                class="btn btn-sm btn-labeled btn-primary">
                                            <span class="btn-label">
                                                <ion-icon name="card-outline"></ion-icon>
                                            </span>Pay &nbsp; $ @Model.Amount
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <script>
                var stripe = Stripe('@HomyTestPublishableKey');

                var payButton = document.getElementById('checkout-button');

                payButton.addEventListener('click', function(event) {
                  event.preventDefault();
                  stripe.redirectToCheckout({
                    sessionId: sessionId
                  });
                });

                var sessionId;
                var paymentId = '@Model.Id';
                    fetch('/management/payments/session/' + paymentId, {
                        method: 'GET',
                        mode: 'same-origin',
                        credentials: 'include',
                        headers: {
                            'Content-Type': 'application/json'
                        }
                    }).then(function (r) {
                        return r.json();
                    }).then(function (response) {
                        debugger;
                        sessionId = response.id;
                    })
                        .catch(error => {
                            console.error('Error:', error);
                        });
                        </script>
                    </div>
                </div>
            </div>
        </section>
    </div>
}
else
{
    <section class="jumbotron jumbotron-fluid jumboHeroImage">
        <div class="container">
            <div class="row pt-5">
                <div class="col-lg-12 pt-5">
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="row d-flex justify-content-center">
            <div class="col-md-4 pl-4 py-xl-4">
                <div class="card shadow">
                    <div class="card-header border-transparent text-center">
                        <h3 class="card-title text-info">
                            <a class="text-info"
                               asp-controller="Rentals"
                               asp-action="Details"
                               asp-route-id="@Model.Id">
                                <strong>@Model.Address</strong>
                            </a>
                        </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">

                        <div class="row px-3">
                            <div class="col-6 text-center">
                                <strong><i class="far fa-calendar-alt mr-1"></i>Payment Request Date</strong>
                                <div class="row">
                                    <div class="col-12">
                                        <hr class="hr-2 mt-1" />
                                    </div>
                                </div>
                                <p class="text-muted">
                                    @Model.Date
                                </p>
                            </div>
                            <div class="col-6 text-center">
                                <strong><i class="far fa-file-alt mr-1"></i>Reason</strong>
                                <div class="row">
                                    <div class="col-12">
                                        <hr class="hr-2 mt-1" />
                                    </div>
                                </div>
                                <p class="text-muted">
                                    @Model.Reason
                                </p>
                            </div>
                        </div>

                        <div class="row px-3">
                            <div class="col-6 text-center">
                                <strong><i class="fas fa-user-tie mr-1"></i>Pay To</strong>
                                <div class="row">
                                    <div class="col-12">
                                        <hr class="hr-2 mt-1" />
                                    </div>
                                </div>
                                <p class="text-muted">
                                    @Model.To
                                </p>
                            </div>
                            <div class="col-6 text-center">
                                <strong><i class="far fa-file-alt mr-1"></i>Status</strong>
                                <div class="row">
                                    <div class="col-12">
                                        <hr class="hr-2 mt-1" />
                                    </div>
                                </div>
                                <span class="badge badge-danger">Pending</span>
                            </div>
                        </div>

                    </div>
                    <!-- /.card-body -->
                    <!-- /.card-footer -->
                    <script src="https://js.stripe.com/v3/"></script>
                    <div id="checkout">
                        <form id="payment-form">
                            <div class="row d-flex justify-content-center">
                                <div class="col-6 py-4 text-center">
                                    <button id="checkout-button"
                                            value="Pay"
                                            class="btn btn-sm btn-labeled btn-primary">
                                        <span class="btn-label">
                                            <ion-icon name="card-outline"></ion-icon>
                                        </span>Pay &nbsp; $ @Model.Amount
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <script>
                var stripe = Stripe('@HomyTestPublishableKey');

                var payButton = document.getElementById('checkout-button');

                payButton.addEventListener('click', function(event) {
                  event.preventDefault();
                  stripe.redirectToCheckout({
                    sessionId: sessionId
                  });
                });

                var sessionId;
                var paymentId = '@Model.Id';

                /*fetch("https://localhost:44319/management/listings/getcity", {
                method: 'GET',
                mode: 'same-origin',
                credentials: 'include',
                body: JSON.stringify({ id: paymentId }),
                headers: {
                  'Content-Type': 'application/json'
                  }
                })
                .then(r =>  r.json().then(data => ({status: r.status, body: data})))
                .then(obj => console.log(obj));*/
                    fetch('/management/payments/session/' + paymentId, {
                        method: 'GET',
                        mode: 'same-origin',
                        credentials: 'include',
                        headers: {
                            'Content-Type': 'application/json'
                        }
                    }).then(function (r) {
                        return r.json();
                    }).then(function (response) {
                        debugger;
                        sessionId = response.id;
                    })
                        .catch(error => {
                            console.error('Error:', error);
                        });
                    </script>
                </div>
            </div>
        </div>
    </section>
}