Web/RPM.Web/Controllers/ContactUsController.cs
namespace RPM.Web.Controllers
{
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Services.Messaging;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.ContactUs;

    using static RPM.Common.GlobalConstants;

    public class ContactUsController : BaseController
    {
        private readonly IEmailSender emailSender;

        public ContactUsController(
            IEmailSender emailSender)
        {
            this.emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = new ContactUsInputModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactUsInputModel model)
        {
            if (this.ModelState.IsValid)
            {
                var email = model.Email;
                var name = model.Name;
                var subject = model.Subject;
                var content = model.Message;

                await this.emailSender.SendPlainEmailAsync(email, name, HomySupportEmail, subject, content, null);

                return this.RedirectToAction(
                    nameof(HomeController.Index),
                    "Home",
                    new { area = string.Empty })
                    .WithSuccess(string.Empty, MessageSentSuccessfully);
            }

            return this.View(model);
        }
    }
}

Web/RPM.Web/Controllers/ListingsController.cs
namespace RPM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using RPM.Data.Models;
    using RPM.Data.Models.Enums;
    using RPM.Services.Common;
    using RPM.Services.Management;
    using RPM.Services.Management.Models;
    using RPM.Web.Areas.Management.Models.Listings;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Listings;

    using static RPM.Common.GlobalConstants;

    [Authorize]
    public class ListingsController : BaseController
    {
        private readonly IListingService listingService;
        private readonly IOwnerListingService ownerListingService;
        private readonly ICityService cityService;
        private readonly ICountryService countryService;
        private readonly ICloudImageService imageService;
        private readonly IImageDbService imageDbService;
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;

        public ListingsController(
            IListingService listingService,
            IOwnerListingService ownerListingService,
            ICityService cityService,
            ICountryService countryService,
            ICloudImageService imageService,
            IImageDbService imageDbService,
            UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            this.listingService = listingService;
            this.ownerListingService = ownerListingService;
            this.cityService = cityService;
            this.countryService = countryService;
            this.imageService = imageService;
            this.imageDbService = imageDbService;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [ActionName("GetCity")]
        public async Task<IActionResult> GetCityAsync(int id)
        {
            var model = await this.cityService.AllCitiesByCountryAsync(id);

            return this.Json(new SelectList(model, "Id", "Name"));
        }

        [ActionName("Create")]
        public async Task<IActionResult> Create()
        {
            var cities = await this.cityService.AllCitiesAsync();
            var countries = await this.countryService.AllCountriesAsync();

            var userId = this.userManager.GetUserId(this.User);
            var user = await this.userManager.FindByIdAsync(userId);

            var userStripeAccount = user.StripeConnectedAccountId;
            bool? hasStripe = true;

            if (string.IsNullOrWhiteSpace(userStripeAccount))
            {
                hasStripe = false;
            }

            var viewModel = new OwnerListingCreateInputModel
            {
                UserHasStripeAccount = hasStripe,
                Cities = cities,
                Countries = countries,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> CreatePostAsync(OwnerListingCreateInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.userManager.GetUserId(this.User);
            var user = await this.userManager.FindByIdAsync(userId);

            // Upload the Image
            var imgResult = await this.imageService
                .UploadImageAsync(model.Image);

            string imgUrl = imgResult.SecureUri.AbsoluteUri;
            string imgPubId = imgResult.PublicId;

            var imageToWrite = new CloudImage
            {
                PictureUrl = imgUrl,
                PicturePublicId = imgPubId,
            };

            var homeCreateServiceModel = new OwnerCreateListingServiceModel
            {
                Name = model.Name,
                Description = model.Description,
                Address = model.Address,
                Price = model.Price,
                CityId = model.CityId,
                Category = model.Category,
                Status = model.Status,
                Owner = user,
                Image = imageToWrite,
            };

            // Create Listing
            bool isCreated = await this.ownerListingService.CreateListingAsync(homeCreateServiceModel);

            if (!isCreated)
            {
                return this.RedirectToAction("Index", "Dashboard", new { area = string.Empty })
                    .WithWarning(string.Empty, CouldNotCreateRecord);
            }

            // Add To Role
            await this.userManager.AddToRoleAsync(user, OwnerRoleName);

            // Referesh authorization since redirect requires the new role auth
            await this.signInManager.RefreshSignInAsync(user);

            // Write Image to DB
            await this.imageDbService.WriteToDatabasebAsync(imgUrl, imgPubId);

            return this.RedirectToAction("Index", "Dashboard", new { area = ManagementArea })
                .WithSuccess(string.Empty, RecordCreatedSuccessfully);
        }

        [ActionName("Details")]
        [AllowAnonymous]
        public async Task<IActionResult> DetailsAsync(string id)
        {
            var model = await this.listingService.GetDetailsAsync(id);

            if (model == null)
            {
                return this.NotFound();
            }

            var viewModel = new PropertyDetailsViewModel
            {
                Id = model.Id,
                Name = model.Name,
                OwnerName = model.OwnerName,
                City = model.City,
                Address = model.Address,
                Country = model.Country,
                Description = model.Description,
                Price = model.Price,
                Status = model.Status.ToString(),
                Category = model.Category.ToString(),
                Image = model.Image,
            };

            return this.View(viewModel);
        }

        [ActionName("AllHouses")]
        [AllowAnonymous]
        public async Task<IActionResult> AllHousesAsync()
        {
            var category = HomeCategory.House;
            var viewModel = new PropertyListByCategoryViewModel
            {
                Properties = await this.listingService.GetAllByCategoryAsync(category),
                Category = category.ToString(),
            };

            return this.View(viewModel);
        }

        [ActionName("AllApartments")]
        [AllowAnonymous]
        public async Task<IActionResult> AllApartmentsAsync()
        {
            var category = HomeCategory.Apartment;

            var viewModel = new PropertyListByCategoryViewModel
            {
                Properties = await this.listingService.GetAllByCategoryAsync(category),
                Category = category.ToString(),
            };

            return this.View(viewModel);
        }

        [ActionName("AllRooms")]
        [AllowAnonymous]
        public async Task<IActionResult> AllRoomsAsync()
        {
            var category = HomeCategory.Room;

            var viewModel = new PropertyListByCategoryViewModel
            {
                Properties = await this.listingService.GetAllByCategoryAsync(category),
                Category = category.ToString(),
            };

            return this.View(viewModel);
        }

        [ActionName("AllToRent")]
        [AllowAnonymous]
        public async Task<IActionResult> AllToRentAsync()
        {
            var status = HomeStatus.ToRent.ToString();

            var viewModel = new PropertyListByStatusViewModel
            {
                Properties = await this.listingService.GetAllByStatusAsync(status),
                Status = status.ToString(),
            };

            return this.View(viewModel);
        }

        [ActionName("AllToManage")]
        [AllowAnonymous]
        public async Task<IActionResult> AllToManageAsync()
        {
            var status = HomeStatus.ToManage.ToString();

            var viewModel = new PropertyListByStatusViewModel
            {
                Properties = await this.listingService.GetAllByStatusAsync(status),
                Status = status.ToString(),
            };

            return this.View(viewModel);
        }
    }
}

Web/RPM.Web/Controllers/ProfileController.cs
namespace RPM.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using RPM.Data;
    using RPM.Data.Models;
    using RPM.Data.Models.Enums;
    using RPM.Services.Common;
    using RPM.Services.Common.Models.Home;
    using RPM.Web.Infrastructure.Extensions;
    using RPM.Web.Models.Home;
    using RPM.Web.Models.Profile;
    using RPM.Web.ViewModels;
    using Stripe;
    using Stripe.Checkout;
    using static RPM.Common.GlobalConstants;

    [Authorize(Roles = TenantRole)]
    public class ProfileController : BaseController
    {
        private readonly UserManager<User> userManager;
        private readonly IPaymentCommonService paymentService;
        private readonly IRentalService rentalService;

        public ProfileController(
            UserManager<User> userManager,
            IPaymentCommonService paymentService,
            IRentalService rentalService)
        {
            this.userManager = userManager;
            this.paymentService = paymentService;
            this.rentalService = rentalService;
        }

        public async Task<IActionResult> Index()
        {
            var userId = this.userManager.GetUserId(this.User);

            var userPayments = await this.paymentService.GetUserPaymentsListAsync(userId);

            var userRentals = await this.rentalService.GetUserRentalsListAsync(userId);
            var viewModel = new ProfileIndexViewModel
            {
                Payments = userPayments,
                Rentals = userRentals,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Pay(string paymentId, string stripeToken)
        {
            var userId = this.userManager.GetUserId(this.User);
            var payment = await this.paymentService.GetPaymentDetailsAsync(paymentId, userId);

            var options = new SessionCreateOptions
            {
                PaymentMethodTypes = new List<string>
                {
                    "card",
                },

                PaymentIntentData = new SessionPaymentIntentDataOptions
                {
                    ApplicationFeeAmount = (long)((payment.Amount * 0.01m) * 100),
                    Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",
                    CaptureMethod = "manual",

                    TransferData = new SessionPaymentIntentTransferDataOptions
                    {
                        Amount = (long)payment.Amount * 100,
                        Destination = payment.ToStripeAccountId,
                    },
                },

                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Name = "Monthly Rent",
                        Description = $"Payment Id: {payment.Id} for rental at {payment.Address}",
                        Amount = (long)payment.Amount * 100,
                        Currency = CurrencyUSD,
                    },
                },
                SuccessUrl = "https://localhost:44319/Management/Stripe/Checkout/success?session_id={CHECKOUT_SESSION_ID}",
                CancelUrl = "https://localhost:44319/Management/Stripe/Checkout/cancel",
            };

            var service = new SessionService();
            Session session = service.Create(options);

            return this.RedirectToAction("Success", new { session_id = session.Id });
        }
    }
}

Web/RPM.Web/Views/Shared/_AlertMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}
@if (!string.IsNullOrEmpty(type))
{
    <div class="row justify-content-center">
        <div class="d-flex justify-content-center alert alert-@type alert-dismissible text-center text-white col-md-4 align-center"
             role="alert"
             style="z-index:1000;
                height:200px;
                position:fixed;
                top:100px;
                bottom:auto;
                margin-left:auto;
                margin-right:auto;
                margin-top:auto;
                margin-bottom:auto;
                border-radius:0;
                border:none;
                text-align:center;
                font-size:25px;
                font-weight:700">
            <button type="button" class="close text-white" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>@title</strong>
            <div class="pl-4"
                 style="margin-top:auto;margin-bottom:auto">@body
            </div>
        </div>
    </div>
}

Web/RPM.Web/Views/Shared/_AvatarImagePartial.cshtml
@if (User.IsInRole(GlobalConstants.AdministratorRoleName))
{
    <img src="~/img/default-admin.png"
         class="img-circle elevation-2" alt="User Image">
}
else if (User.IsInRole(GlobalConstants.OwnerRoleName))
{
    <img src="~/img/default-owner.png"
         class="img-circle elevation-2" alt="User Image">
}
else if (User.IsInRole(GlobalConstants.ManagerRoleName))
{
    <img src="~/img/default-manager.png"
         class="img-circle elevation-2" alt="User Image">
}

Web/RPM.Web/Views/Shared/_ButtonCRUDPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a class="btn btn-dark text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="far fa-trash-alt"></i>
        </a>
    </div>
</td>

Web/RPM.Web/Views/Shared/_ButtonCreatePartial.cshtml
@if (this.User.IsInRole(OwnerRoleName))
{
    <p class="text-left p-0 m-0">
        <a asp-controller="Listings" asp-action="Create" class="btn btn-sm btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
    </p>
}
else
{
    <p>
        <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Create New</a>
    </p>
}
    

Web/RPM.Web/Views/Shared/_Layout.cshtml
@using RPM.Common
@using RPM.Data.Models
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homy | Home Page</title>

    <environment names="Development">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

        <!-- Css Styles -->
        <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/flaticon.css" type="text/css">
        <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
        <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
        <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/style.css" type="text/css">

        <!-- Font Awesome -->
        <link href="~/themes/admin/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- overlayScrollbars -->
        <link rel="stylesheet" href="~/themes/admin/dist/css/adminlte.min.css">

        <!-- Bootstrap -->
        <link href="~/themes/admin/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />

        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    </environment>

    <environment names="Staging,Production">
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

        <!-- Css Styles -->
        <link rel="stylesheet" href="~/css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/font-awesome.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/flaticon.css" type="text/css">
        <link rel="stylesheet" href="~/css/nice-select.css" type="text/css">
        <link rel="stylesheet" href="~/css/owl.carousel.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/magnific-popup.css" type="text/css">
        <link rel="stylesheet" href="~/css/slicknav.min.css" type="text/css">
        <link rel="stylesheet" href="~/css/style.css" type="text/css">

        <!-- Font Awesome -->
        <link href="~/themes/admin/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <!-- overlayScrollbars -->
        <link rel="stylesheet" href="~/themes/admin/dist/css/adminlte.min.css">
        <!-- Bootstrap -->
        <link href="~/themes/admin/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <partial name="_FaviconsPartial" />
    </environment>
</head>

<body>
    <!-- Page Preloder -->

    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->

    <header class="header-section">
        <div class="container-fluid">
            <div class="logo pl-5">
                <a class="navbar-brand"
                   asp-area=""
                   asp-controller="Home"
                   asp-action="Index"
                   style="margin-top: -18px;">
                    <img src="~/img/Homy_Graphic Logo_4.png" class="image-fluid">
                </a>
            </div>
            @if (this.SignInManager.IsSignedIn(this.User))
            {
                if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                {
                    <a asp-area="Administration" asp-controller="Dashboard" asp-action="Index" title="Admin">Admin</a>
                }
                <nav class="main-menu mobile-menu">
                    <ul>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="ContactUs" asp-action="Index">Help</a></li>
                    </ul>
                </nav>
                <div class="header-right" id="MyTopnav">
                    <div class="user-access">

                        <a asp-area="Identity" asp-page="/Account/Manage/Index"
                           title="Manage" style="color:#FF5581" class="pr-2">Hello @(this.User.Identity.Name)!</a>

                        @if (this.User.IsInRole(GlobalConstants.TenantRole))
                        {
                            <a asp-controller="Profile" asp-action="Index">
                                Profile
                            </a>
                        }
                        else if (this.User.IsInRole(GlobalConstants.ManagerRoleName))
                        {
                            <a asp-controller="Dashboard" asp-action="Index">
                                Dashboard
                            </a>
                        }

                    </div>
                    @if (!this.User.IsInRole(TenantRole) && !this.User.IsInRole(ManagerRoleName))
                    {
                        <a asp-area=""
                           asp-controller="Listings"
                           asp-action="Create"
                           title="Create Listing"
                           class="primary-btn ml-0 px-4">Add Listing</a>
                    }
                    <a asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@(this.Url.Action("Index", "Home", new { area = string.Empty }))" class="primary-btn px-3 ml-2 mr-4" style="background-color: #01BFE1">Logout</a>
                </div>
                <div id="mobile-menu-wrap"></div>
            }

            else
            {
                <nav class="main-menu mobile-menu">
                    <ul mr-auto>
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="ContactUs" asp-action="Index">Contact</a></li>
                        <li></li>
                        <li></li>
                        <li></li>
                        <li></li>

                    </ul>
                </nav>

                <div class="header-right">
                    <div class="user-access">
                        <a asp-area="Identity" asp-page="/Account/Register">Register/</a>
                        <a asp-area="Identity" asp-page="/Account/Login">Login</a>
                    </div>
                    <a asp-area="Identity"
                       asp-page="/Account/Login"
                       title="Create Listing"
                       class="primary-btn ml-0 px-4">Add Listing</a>
                </div>
                <div id="mobile-menu-wrap"></div>
            }
        </div>
    </header>

    <!-- Header End -->

        <main role="main"
              style="min-height:100vh;">
            <!--<partial name="_AlertMessages" />-->

            <partial name="_AlertMessages" />

            @this.RenderBody()

            <partial name="_CookieConsentPartial" />
        </main>

        <!-- Footer Section Begin -->
        <footer class="footer-section spad" style="position:absolute;width:100%;">
            <div class="container">
                <span class="text-primary">&copy; @DateTime.Now.Year - @GlobalConstants.SystemName &nbsp;</span>
                <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

                <div class="row footer-bottom pt-4">
                    <div class="col-lg-5 order-2 order-lg-1">
                        <div class="copyright pb-0 mb-0">
                            <p class="text-secondary">
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                All rights reserved | This template is made by<a href="https://colorlib.com" target="_blank">&nbsp; Colorlib and proudly edited by Darin Rusev</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer Section End -->

        <environment names="Development">

            <script src="~/js/jquery-3.3.1.min.js"></script>
            <script src="~/js/bootstrap.min.js"></script>
            <script src="~/js/jquery.magnific-popup.min.js"></script>
            <script src="~/js/jquery.slicknav.js"></script>
            <script src="~/js/owl.carousel.min.js"></script>
            <script src="~/js/jquery.nice-select.min.js"></script>
            <script src="~/js/mixitup.min.js"></script>
            <script src="~/js/main.js"></script>

            <!-- jQuery -->
            <script src="~/themes/admin/plugins/jquery/jquery.min.js"></script>
            <!-- Bootstrap 4 -->
            <script src="~/themes/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
            <!-- AdminLTE App -->
            <script src="~/themes/admin/dist/js/adminlte.min.js"></script>
            <!-- AdminLTE for demo purposes -->
            <script src="~/themes/admin/dist/js/demo.js"></script>
            <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
            <script src="~/js/paginator.js"></script>

        </environment>

        <environment names="Staging,Production">
            <script src="~/js/jquery-3.3.1.min.js"></script>
            <script src="~/js/bootstrap.min.js"></script>
            <script src="~/js/jquery.magnific-popup.min.js"></script>
            <script src="~/js/jquery.slicknav.js"></script>
            <script src="~/js/owl.carousel.min.js"></script>
            <script src="~/js/jquery.nice-select.min.js"></script>
            <script src="~/js/mixitup.min.js"></script>
            <script src="~/js/main.js"></script>

            <!-- jQuery -->
            <script src="~/themes/admin/plugins/jquery/jquery.min.js"></script>
            <!-- Bootstrap 4 -->
            <script src="~/themes/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
            <!-- AdminLTE App -->
            <script src="~/themes/admin/dist/js/adminlte.min.js"></script>
            <!-- AdminLTE for demo purposes -->
            <script src="~/themes/admin/dist/js/demo.js"></script>
            <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
            <script src="~/js/paginator.js"></script>

        </environment>

    @this.RenderSection("Scripts", required: false)

</body>
</html>

Web/RPM.Web/Views/Shared/_OwnerSuccessPartial.cshtml
@model CheckoutPaymentViewModel

<body class="success-bg">
    <div class="content-wrapper"></div>
    <section class="content pb-4"
             style="padding-top: 120px; margin-left: auto; margin-right: auto;">
        <div class="row d-flex justify-content-center">

            <div class="row p-3 mx-auto mt-4">
                <div class="form-area">
                    <div class="col-md-12 pb-4">
                        <p>
                            <a class="primary-btn px-1 bg-transparent text-primary">
                                Thank you! Your payment was successful!
                            </a>
                        </p>
                        <ul class="pb-4 mb-4">
                            @*<li><strong>Payment reason:</strong> Model.Reason</li>
                                <li><strong>Amount paid:</strong> Model.Amount</li>
                                <li><strong>Recipient:</strong> Model.To</li>*@
                            <li><strong>Payment reason:</strong> @Model.Reason</li>
                            <li><strong>Amount paid:</strong> $ @Model.Amount</li>
                            <li><strong>Recipient:</strong> @Model.To</li>
                            <li><strong>Property Address:</strong> @Model.Address</li>
                            @*<li><strong>Transaction Date:</strong> @Model.TransactionDate</li>*@
                        </ul>
                    </div>
                    @if (this.User.IsInRole(OwnerRoleName))
                    {
                        <div class="col-md-6 pt-4 mt-4 mx-auto">
                            <a asp-area="Management"
                               asp-controller="Dashboard"
                               asp-action="Index"
                               class="shadow btn btn-block btn-primary text-white">
                                Back to Dashboard
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="col-md-6 pt-4 mt-4 mx-auto">
                            <a asp-controller="Profile"
                               asp-action="Index"
                               class="shadow btn btn-block btn-primary text-white">
                                Back to Profile
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</body>

Web/RPM.Web/Views/Shared/_PropertyListByCategoryPartial.cshtml
@model ICollection<PropertyCountServiceModel>

@foreach (var category in Model)
{
    <div class="col-md-4">
        <div class="pb-0 mb-0 categories-item set-bg" data-setbg="@category.ExampleImage">
            <a href="@category.ExampleImage" class="img-hover pop-up"><img src="/img/zoom.png" alt=""></a>
            <div class="categories-text">
                <h4>@category.CategoryName</h4>
                <p>@category.Count Listings</p>
                <a asp-controller="Listings" asp-action="All@(category.CategoryName)">View All</a>
            </div>
        </div>
    </div>
}

Web/RPM.Web/Views/Shared/_PropertyListByStatusPartial.cshtml
@model IEnumerable<PropertyListServiceModel>

@foreach (var home in Model)
{
    <div class="col-md-3">
        <div class="pb-0 mb-0 categories-item set-bg" data-setbg="@home.Image">
            <a href="@home.Image" class="img-hover pop-up"><img src="/img/zoom.png" alt=""></a>
            <div class="categories-text">
                <h4>@(home.Name.Length <= 30 ? home.Name : home.Name.Substring(0, 30) + "...")</h4>
                <p>@home.City, @home.Country</p>
                <a asp-controller="Listings" asp-action="Details" asp-route-id="@home.Id">View Details</a>
            </div>
        </div>
    </div>
}